// Package models contains generated code for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"

	"github.com/google/uuid"
)

// Customer represents a row from 'public.customers'.
type Customer struct {
	ID       uuid.UUID `json:"id"`       // id
	Name     string    `json:"name"`     // name
	Password string    `json:"password"` // password
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Customer] exists in the database.
func (c *Customer) Exists() bool {
	return c._exists
}

// Deleted returns true when the [Customer] has been marked for deletion
// from the database.
func (c *Customer) Deleted() bool {
	return c._deleted
}

// Insert inserts the [Customer] to the database.
func (c *Customer) Insert(ctx context.Context, db DB) error {
	switch {
	case c._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case c._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (manual)
	const sqlstr = `INSERT INTO public.customers (` +
		`id, name, password` +
		`) VALUES (` +
		`$1, $2, $3` +
		`)`
	// run
	logf(sqlstr, c.ID, c.Name, c.Password)
	if _, err := db.ExecContext(ctx, sqlstr, c.ID, c.Name, c.Password); err != nil {
		return logerror(err)
	}
	// set exists
	c._exists = true
	return nil
}

// Update updates a [Customer] in the database.
func (c *Customer) Update(ctx context.Context, db DB) error {
	switch {
	case !c._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case c._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.customers SET ` +
		`name = $1, password = $2 ` +
		`WHERE id = $3`
	// run
	logf(sqlstr, c.Name, c.Password, c.ID)
	if _, err := db.ExecContext(ctx, sqlstr, c.Name, c.Password, c.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Customer] to the database.
func (c *Customer) Save(ctx context.Context, db DB) error {
	if c.Exists() {
		return c.Update(ctx, db)
	}
	return c.Insert(ctx, db)
}

// Upsert performs an upsert for [Customer].
func (c *Customer) Upsert(ctx context.Context, db DB) error {
	switch {
	case c._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.customers (` +
		`id, name, password` +
		`) VALUES (` +
		`$1, $2, $3` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`name = EXCLUDED.name, password = EXCLUDED.password `
	// run
	logf(sqlstr, c.ID, c.Name, c.Password)
	if _, err := db.ExecContext(ctx, sqlstr, c.ID, c.Name, c.Password); err != nil {
		return logerror(err)
	}
	// set exists
	c._exists = true
	return nil
}

// Delete deletes the [Customer] from the database.
func (c *Customer) Delete(ctx context.Context, db DB) error {
	switch {
	case !c._exists: // doesn't exist
		return nil
	case c._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.customers ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, c.ID)
	if _, err := db.ExecContext(ctx, sqlstr, c.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	c._deleted = true
	return nil
}

// CustomerByNamePassword retrieves a row from 'public.customers' as a [Customer].
//
// Generated from index 'customers_name_password_key'.
func CustomerByNamePassword(ctx context.Context, db DB, name, password string) (*Customer, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, name, password ` +
		`FROM public.customers ` +
		`WHERE name = $1 AND password = $2`
	// run
	logf(sqlstr, name, password)
	c := Customer{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, name, password).Scan(&c.ID, &c.Name, &c.Password); err != nil {
		return nil, logerror(err)
	}
	return &c, nil
}

// CustomerByID retrieves a row from 'public.customers' as a [Customer].
//
// Generated from index 'customers_pkey'.
func CustomerByID(ctx context.Context, db DB, id uuid.UUID) (*Customer, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, name, password ` +
		`FROM public.customers ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	c := Customer{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&c.ID, &c.Name, &c.Password); err != nil {
		return nil, logerror(err)
	}
	return &c, nil
}
