package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"

	"github.com/lib/pq"
)

// ArmorByBytea calls the stored function 'public.armor(bytea) text' on db.
func ArmorByBytea(ctx context.Context, db DB, p0 []byte) (string, error) {
	// call public.armor
	const sqlstr = `SELECT * FROM public.armor($1)`
	// run
	var r0 string
	logf(sqlstr, p0)
	if err := db.QueryRowContext(ctx, sqlstr, p0).Scan(&r0); err != nil {
		return "", logerror(err)
	}
	return r0, nil
}

// ArmorByByteaTextAndText calls the stored function 'public.armor(bytea, text, text) text' on db.
func ArmorByByteaTextAndText(ctx context.Context, db DB, p0 []byte, p1, p2 pq.StringArray) (string, error) {
	// call public.armor
	const sqlstr = `SELECT * FROM public.armor($1, $2, $3)`
	// run
	var r0 string
	logf(sqlstr, p0, p1, p2)
	if err := db.QueryRowContext(ctx, sqlstr, p0, p1, p2).Scan(&r0); err != nil {
		return "", logerror(err)
	}
	return r0, nil
}
