package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// Encrypt calls the stored function 'public.encrypt(bytea, bytea, text) bytea' on db.
func Encrypt(ctx context.Context, db DB, p0, p1 []byte, p2 string) ([]byte, error) {
	// call public.encrypt
	const sqlstr = `SELECT * FROM public.encrypt($1, $2, $3)`
	// run
	var r0 []byte
	logf(sqlstr, p0, p1, p2)
	if err := db.QueryRowContext(ctx, sqlstr, p0, p1, p2).Scan(&r0); err != nil {
		return nil, logerror(err)
	}
	return r0, nil
}
