package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// PgpSymEncryptByTextAndText calls the stored function 'public.pgp_sym_encrypt(text, text) bytea' on db.
func PgpSymEncryptByTextAndText(ctx context.Context, db DB, p0, p1 string) ([]byte, error) {
	// call public.pgp_sym_encrypt
	const sqlstr = `SELECT * FROM public.pgp_sym_encrypt($1, $2)`
	// run
	var r0 []byte
	logf(sqlstr, p0, p1)
	if err := db.QueryRowContext(ctx, sqlstr, p0, p1).Scan(&r0); err != nil {
		return nil, logerror(err)
	}
	return r0, nil
}

// PgpSymEncryptByTextTextAndText calls the stored function 'public.pgp_sym_encrypt(text, text, text) bytea' on db.
func PgpSymEncryptByTextTextAndText(ctx context.Context, db DB, p0, p1, p2 string) ([]byte, error) {
	// call public.pgp_sym_encrypt
	const sqlstr = `SELECT * FROM public.pgp_sym_encrypt($1, $2, $3)`
	// run
	var r0 []byte
	logf(sqlstr, p0, p1, p2)
	if err := db.QueryRowContext(ctx, sqlstr, p0, p1, p2).Scan(&r0); err != nil {
		return nil, logerror(err)
	}
	return r0, nil
}
