package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// PgpKeyID calls the stored function 'public.pgp_key_id(bytea) text' on db.
func PgpKeyID(ctx context.Context, db DB, p0 []byte) (string, error) {
	// call public.pgp_key_id
	const sqlstr = `SELECT * FROM public.pgp_key_id($1)`
	// run
	var r0 string
	logf(sqlstr, p0)
	if err := db.QueryRowContext(ctx, sqlstr, p0).Scan(&r0); err != nil {
		return "", logerror(err)
	}
	return r0, nil
}
