package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// PgpPubDecryptByteaByByteaAndBytea calls the stored function 'public.pgp_pub_decrypt_bytea(bytea, bytea) bytea' on db.
func PgpPubDecryptByteaByByteaAndBytea(ctx context.Context, db DB, p0, p1 []byte) ([]byte, error) {
	// call public.pgp_pub_decrypt_bytea
	const sqlstr = `SELECT * FROM public.pgp_pub_decrypt_bytea($1, $2)`
	// run
	var r0 []byte
	logf(sqlstr, p0, p1)
	if err := db.QueryRowContext(ctx, sqlstr, p0, p1).Scan(&r0); err != nil {
		return nil, logerror(err)
	}
	return r0, nil
}

// PgpPubDecryptByteaByByteaByteaAndText calls the stored function 'public.pgp_pub_decrypt_bytea(bytea, bytea, text) bytea' on db.
func PgpPubDecryptByteaByByteaByteaAndText(ctx context.Context, db DB, p0, p1 []byte, p2 string) ([]byte, error) {
	// call public.pgp_pub_decrypt_bytea
	const sqlstr = `SELECT * FROM public.pgp_pub_decrypt_bytea($1, $2, $3)`
	// run
	var r0 []byte
	logf(sqlstr, p0, p1, p2)
	if err := db.QueryRowContext(ctx, sqlstr, p0, p1, p2).Scan(&r0); err != nil {
		return nil, logerror(err)
	}
	return r0, nil
}

// PgpPubDecryptByteaByByteaByteaTextAndText calls the stored function 'public.pgp_pub_decrypt_bytea(bytea, bytea, text, text) bytea' on db.
func PgpPubDecryptByteaByByteaByteaTextAndText(ctx context.Context, db DB, p0, p1 []byte, p2, p3 string) ([]byte, error) {
	// call public.pgp_pub_decrypt_bytea
	const sqlstr = `SELECT * FROM public.pgp_pub_decrypt_bytea($1, $2, $3, $4)`
	// run
	var r0 []byte
	logf(sqlstr, p0, p1, p2, p3)
	if err := db.QueryRowContext(ctx, sqlstr, p0, p1, p2, p3).Scan(&r0); err != nil {
		return nil, logerror(err)
	}
	return r0, nil
}
