package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"

	"github.com/google/uuid"
)

// StreamCred represents a row from 'public.stream_creds'.
type StreamCred struct {
	ID         uuid.UUID  `json:"id"`          // id
	CustomerID uuid.UUID  `json:"customer_id"` // customer_id
	AuthCode   string     `json:"auth_code"`   // auth_code
	StreamType StreamType `json:"stream_type"` // stream_type
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [StreamCred] exists in the database.
func (sc *StreamCred) Exists() bool {
	return sc._exists
}

// Deleted returns true when the [StreamCred] has been marked for deletion
// from the database.
func (sc *StreamCred) Deleted() bool {
	return sc._deleted
}

// Insert inserts the [StreamCred] to the database.
func (sc *StreamCred) Insert(ctx context.Context, db DB) error {
	switch {
	case sc._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case sc._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (manual)
	const sqlstr = `INSERT INTO public.stream_creds (` +
		`id, customer_id, auth_code, stream_type` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`)`
	// run
	logf(sqlstr, sc.ID, sc.CustomerID, sc.AuthCode, sc.StreamType)
	if _, err := db.ExecContext(ctx, sqlstr, sc.ID, sc.CustomerID, sc.AuthCode, sc.StreamType); err != nil {
		return logerror(err)
	}
	// set exists
	sc._exists = true
	return nil
}

// Update updates a [StreamCred] in the database.
func (sc *StreamCred) Update(ctx context.Context, db DB) error {
	switch {
	case !sc._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case sc._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.stream_creds SET ` +
		`customer_id = $1, auth_code = $2, stream_type = $3 ` +
		`WHERE id = $4`
	// run
	logf(sqlstr, sc.CustomerID, sc.AuthCode, sc.StreamType, sc.ID)
	if _, err := db.ExecContext(ctx, sqlstr, sc.CustomerID, sc.AuthCode, sc.StreamType, sc.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [StreamCred] to the database.
func (sc *StreamCred) Save(ctx context.Context, db DB) error {
	if sc.Exists() {
		return sc.Update(ctx, db)
	}
	return sc.Insert(ctx, db)
}

// Upsert performs an upsert for [StreamCred].
func (sc *StreamCred) Upsert(ctx context.Context, db DB) error {
	switch {
	case sc._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.stream_creds (` +
		`id, customer_id, auth_code, stream_type` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`customer_id = EXCLUDED.customer_id, auth_code = EXCLUDED.auth_code, stream_type = EXCLUDED.stream_type `
	// run
	logf(sqlstr, sc.ID, sc.CustomerID, sc.AuthCode, sc.StreamType)
	if _, err := db.ExecContext(ctx, sqlstr, sc.ID, sc.CustomerID, sc.AuthCode, sc.StreamType); err != nil {
		return logerror(err)
	}
	// set exists
	sc._exists = true
	return nil
}

// Delete deletes the [StreamCred] from the database.
func (sc *StreamCred) Delete(ctx context.Context, db DB) error {
	switch {
	case !sc._exists: // doesn't exist
		return nil
	case sc._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.stream_creds ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, sc.ID)
	if _, err := db.ExecContext(ctx, sqlstr, sc.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	sc._deleted = true
	return nil
}

// StreamCredByCustomerIDStreamType retrieves a row from 'public.stream_creds' as a [StreamCred].
//
// Generated from index 'stream_creds_customer_id_stream_type_key'.
func StreamCredByCustomerIDStreamType(ctx context.Context, db DB, customerID uuid.UUID, streamType StreamType) (*StreamCred, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, customer_id, auth_code, stream_type ` +
		`FROM public.stream_creds ` +
		`WHERE customer_id = $1 AND stream_type = $2`
	// run
	logf(sqlstr, customerID, streamType)
	sc := StreamCred{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, customerID, streamType).Scan(&sc.ID, &sc.CustomerID, &sc.AuthCode, &sc.StreamType); err != nil {
		return nil, logerror(err)
	}
	return &sc, nil
}

// StreamCredByID retrieves a row from 'public.stream_creds' as a [StreamCred].
//
// Generated from index 'stream_creds_pkey'.
func StreamCredByID(ctx context.Context, db DB, id uuid.UUID) (*StreamCred, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, customer_id, auth_code, stream_type ` +
		`FROM public.stream_creds ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	sc := StreamCred{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&sc.ID, &sc.CustomerID, &sc.AuthCode, &sc.StreamType); err != nil {
		return nil, logerror(err)
	}
	return &sc, nil
}

// Customer returns the Customer associated with the [StreamCred]'s (CustomerID).
//
// Generated from foreign key 'fk_customer'.
func (sc *StreamCred) Customer(ctx context.Context, db DB) (*Customer, error) {
	return CustomerByID(ctx, db, sc.CustomerID)
}
