package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql/driver"
	"fmt"
)

// StreamType is the 'stream_type' enum type from schema 'public'.
type StreamType uint16

// StreamType values.
const (
	// StreamTypeSpotify is the 'SPOTIFY' stream_type.
	StreamTypeSpotify StreamType = 1
	// StreamTypeTidal is the 'TIDAL' stream_type.
	StreamTypeTidal StreamType = 2
)

// String satisfies the [fmt.Stringer] interface.
func (st StreamType) String() string {
	switch st {
	case StreamTypeSpotify:
		return "SPOTIFY"
	case StreamTypeTidal:
		return "TIDAL"
	}
	return fmt.Sprintf("StreamType(%d)", st)
}

// MarshalText marshals [StreamType] into text.
func (st StreamType) MarshalText() ([]byte, error) {
	return []byte(st.String()), nil
}

// UnmarshalText unmarshals [StreamType] from text.
func (st *StreamType) UnmarshalText(buf []byte) error {
	switch str := string(buf); str {
	case "SPOTIFY":
		*st = StreamTypeSpotify
	case "TIDAL":
		*st = StreamTypeTidal
	default:
		return ErrInvalidStreamType(str)
	}
	return nil
}

// Value satisfies the [driver.Valuer] interface.
func (st StreamType) Value() (driver.Value, error) {
	return st.String(), nil
}

// Scan satisfies the [sql.Scanner] interface.
func (st *StreamType) Scan(v interface{}) error {
	switch x := v.(type) {
	case []byte:
		return st.UnmarshalText(x)
	case string:
		return st.UnmarshalText([]byte(x))
	}
	return ErrInvalidStreamType(fmt.Sprintf("%T", v))
}

// NullStreamType represents a null 'stream_type' enum for schema 'public'.
type NullStreamType struct {
	StreamType StreamType
	// Valid is true if [StreamType] is not null.
	Valid bool
}

// Value satisfies the [driver.Valuer] interface.
func (nst NullStreamType) Value() (driver.Value, error) {
	if !nst.Valid {
		return nil, nil
	}
	return nst.StreamType.Value()
}

// Scan satisfies the [sql.Scanner] interface.
func (nst *NullStreamType) Scan(v interface{}) error {
	if v == nil {
		nst.StreamType, nst.Valid = 0, false
		return nil
	}
	err := nst.StreamType.Scan(v)
	nst.Valid = err == nil
	return err
}

// ErrInvalidStreamType is the invalid [StreamType] error.
type ErrInvalidStreamType string

// Error satisfies the error interface.
func (err ErrInvalidStreamType) Error() string {
	return fmt.Sprintf("invalid StreamType(%s)", string(err))
}
