package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// TokenStore represents a row from 'public.token_store'.
type TokenStore struct {
	Token       string    `json:"token"`        // token
	CustomerID  uuid.UUID `json:"customer_id"`  // customer_id
	ExpireAfter time.Time `json:"expire_after"` // expire_after
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [TokenStore] exists in the database.
func (ts *TokenStore) Exists() bool {
	return ts._exists
}

// Deleted returns true when the [TokenStore] has been marked for deletion
// from the database.
func (ts *TokenStore) Deleted() bool {
	return ts._deleted
}

// Insert inserts the [TokenStore] to the database.
func (ts *TokenStore) Insert(ctx context.Context, db DB) error {
	switch {
	case ts._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case ts._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (manual)
	const sqlstr = `INSERT INTO public.token_store (` +
		`token, customer_id, expire_after` +
		`) VALUES (` +
		`$1, $2, $3` +
		`)`
	// run
	logf(sqlstr, ts.Token, ts.CustomerID, ts.ExpireAfter)
	if _, err := db.ExecContext(ctx, sqlstr, ts.Token, ts.CustomerID, ts.ExpireAfter); err != nil {
		return logerror(err)
	}
	// set exists
	ts._exists = true
	return nil
}

// Update updates a [TokenStore] in the database.
func (ts *TokenStore) Update(ctx context.Context, db DB) error {
	switch {
	case !ts._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case ts._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.token_store SET ` +
		`customer_id = $1, expire_after = $2 ` +
		`WHERE token = $3`
	// run
	logf(sqlstr, ts.CustomerID, ts.ExpireAfter, ts.Token)
	if _, err := db.ExecContext(ctx, sqlstr, ts.CustomerID, ts.ExpireAfter, ts.Token); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [TokenStore] to the database.
func (ts *TokenStore) Save(ctx context.Context, db DB) error {
	if ts.Exists() {
		return ts.Update(ctx, db)
	}
	return ts.Insert(ctx, db)
}

// Upsert performs an upsert for [TokenStore].
func (ts *TokenStore) Upsert(ctx context.Context, db DB) error {
	switch {
	case ts._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.token_store (` +
		`token, customer_id, expire_after` +
		`) VALUES (` +
		`$1, $2, $3` +
		`)` +
		` ON CONFLICT (token) DO ` +
		`UPDATE SET ` +
		`customer_id = EXCLUDED.customer_id, expire_after = EXCLUDED.expire_after `
	// run
	logf(sqlstr, ts.Token, ts.CustomerID, ts.ExpireAfter)
	if _, err := db.ExecContext(ctx, sqlstr, ts.Token, ts.CustomerID, ts.ExpireAfter); err != nil {
		return logerror(err)
	}
	// set exists
	ts._exists = true
	return nil
}

// Delete deletes the [TokenStore] from the database.
func (ts *TokenStore) Delete(ctx context.Context, db DB) error {
	switch {
	case !ts._exists: // doesn't exist
		return nil
	case ts._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.token_store ` +
		`WHERE token = $1`
	// run
	logf(sqlstr, ts.Token)
	if _, err := db.ExecContext(ctx, sqlstr, ts.Token); err != nil {
		return logerror(err)
	}
	// set deleted
	ts._deleted = true
	return nil
}

// TokenStoreByToken retrieves a row from 'public.token_store' as a [TokenStore].
//
// Generated from index 'token_store_pkey'.
func TokenStoreByToken(ctx context.Context, db DB, token string) (*TokenStore, error) {
	// query
	const sqlstr = `SELECT ` +
		`token, customer_id, expire_after ` +
		`FROM public.token_store ` +
		`WHERE token = $1`
	// run
	logf(sqlstr, token)
	ts := TokenStore{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, token).Scan(&ts.Token, &ts.CustomerID, &ts.ExpireAfter); err != nil {
		return nil, logerror(err)
	}
	return &ts, nil
}

// Customer returns the Customer associated with the [TokenStore]'s (CustomerID).
//
// Generated from foreign key 'fk_customer'.
func (ts *TokenStore) Customer(ctx context.Context, db DB) (*Customer, error) {
	return CustomerByID(ctx, db, ts.CustomerID)
}
