// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: authorisation/login/v1/login.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthoriseService_Login_FullMethodName = "/authorisation.login.v1.AuthoriseService/Login"
)

// AuthoriseServiceClient is the client API for AuthoriseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthoriseServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type authoriseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthoriseServiceClient(cc grpc.ClientConnInterface) AuthoriseServiceClient {
	return &authoriseServiceClient{cc}
}

func (c *authoriseServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AuthoriseService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthoriseServiceServer is the server API for AuthoriseService service.
// All implementations must embed UnimplementedAuthoriseServiceServer
// for forward compatibility.
type AuthoriseServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	mustEmbedUnimplementedAuthoriseServiceServer()
}

// UnimplementedAuthoriseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthoriseServiceServer struct{}

func (UnimplementedAuthoriseServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthoriseServiceServer) mustEmbedUnimplementedAuthoriseServiceServer() {}
func (UnimplementedAuthoriseServiceServer) testEmbeddedByValue()                          {}

// UnsafeAuthoriseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthoriseServiceServer will
// result in compilation errors.
type UnsafeAuthoriseServiceServer interface {
	mustEmbedUnimplementedAuthoriseServiceServer()
}

func RegisterAuthoriseServiceServer(s grpc.ServiceRegistrar, srv AuthoriseServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuthoriseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthoriseService_ServiceDesc, srv)
}

func _AuthoriseService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthoriseServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthoriseService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthoriseServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthoriseService_ServiceDesc is the grpc.ServiceDesc for AuthoriseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthoriseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authorisation.login.v1.AuthoriseService",
	HandlerType: (*AuthoriseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AuthoriseService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authorisation/login/v1/login.proto",
}
