apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorisation
spec:
  selector:
    matchLabels:
      app: authorisation
  replicas: 2
  template:
    metadata:
      labels:
        app: authorisation
    spec:
      containers:
      - name: authorisation
        image: sabaruto/authorisation:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9090
      imagePullSecrets:
      - name: regcred
