apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: authorisation-postgres
spec:
  selector:
    matchLabels:
      app: authorisation-postgres
  serviceName: authorisation-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: authorisation-postgres
    spec:
      containers:
      - name: authorisation-postgres
        image: sabaruto/postgresql:latest
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-creds
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-creds
                key: password
        ports:
        - containerPort: 5432
          name: web
        volumeMounts:
        - name: www
          mountPath: /var/lib/postresql/data
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
