spring:
  application:
    name: streaming-service-merger
api:
  spotify:
    client_id: ${SPOTIFY_CLIENT_ID}
    client_secret: ${SPOTIFY_CLIENT_SECRET}
  tidal:
    client_id: ${TIDAL_CLIENT_ID}
    client_secret: ${TIDAL_CLIENT_SECRET}
