package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// Crypt calls the stored function 'public.crypt(text, text) text' on db.
func Crypt(ctx context.Context, db DB, p0, p1 string) (string, error) {
	// call public.crypt
	const sqlstr = `SELECT * FROM public.crypt($1, $2)`
	// run
	var r0 string
	logf(sqlstr, p0, p1)
	if err := db.QueryRowContext(ctx, sqlstr, p0, p1).Scan(&r0); err != nil {
		return "", logerror(err)
	}
	return r0, nil
}
