package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// Dearmor calls the stored function 'public.dearmor(text) bytea' on db.
func Dearmor(ctx context.Context, db DB, p0 string) ([]byte, error) {
	// call public.dearmor
	const sqlstr = `SELECT * FROM public.dearmor($1)`
	// run
	var r0 []byte
	logf(sqlstr, p0)
	if err := db.QueryRowContext(ctx, sqlstr, p0).Scan(&r0); err != nil {
		return nil, logerror(err)
	}
	return r0, nil
}
