package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// EncryptIv calls the stored function 'public.encrypt_iv(bytea, bytea, bytea, text) bytea' on db.
func EncryptIv(ctx context.Context, db DB, p0, p1, p2 []byte, p3 string) ([]byte, error) {
	// call public.encrypt_iv
	const sqlstr = `SELECT * FROM public.encrypt_iv($1, $2, $3, $4)`
	// run
	var r0 []byte
	logf(sqlstr, p0, p1, p2, p3)
	if err := db.QueryRowContext(ctx, sqlstr, p0, p1, p2, p3).Scan(&r0); err != nil {
		return nil, logerror(err)
	}
	return r0, nil
}
