package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"

	"github.com/google/uuid"
)

// GenRandomUUID calls the stored function 'public.gen_random_uuid() uuid' on db.
func GenRandomUUID(ctx context.Context, db DB) (uuid.UUID, error) {
	// call public.gen_random_uuid
	const sqlstr = `SELECT * FROM public.gen_random_uuid()`
	// run
	var r0 uuid.UUID
	logf(sqlstr)
	if err := db.QueryRowContext(ctx, sqlstr).Scan(&r0); err != nil {
		return uuid.UUID{}, logerror(err)
	}
	return r0, nil
}
