package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// GenRandomBytes calls the stored function 'public.gen_random_bytes(integer) bytea' on db.
func GenRandomBytes(ctx context.Context, db DB, p0 int) ([]byte, error) {
	// call public.gen_random_bytes
	const sqlstr = `SELECT * FROM public.gen_random_bytes($1)`
	// run
	var r0 []byte
	logf(sqlstr, p0)
	if err := db.QueryRowContext(ctx, sqlstr, p0).Scan(&r0); err != nil {
		return nil, logerror(err)
	}
	return r0, nil
}
