package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// GenSaltByText calls the stored function 'public.gen_salt(text) text' on db.
func GenSaltByText(ctx context.Context, db DB, p0 string) (string, error) {
	// call public.gen_salt
	const sqlstr = `SELECT * FROM public.gen_salt($1)`
	// run
	var r0 string
	logf(sqlstr, p0)
	if err := db.QueryRowContext(ctx, sqlstr, p0).Scan(&r0); err != nil {
		return "", logerror(err)
	}
	return r0, nil
}

// GenSaltByTextAndInteger calls the stored function 'public.gen_salt(text, integer) text' on db.
func GenSaltByTextAndInteger(ctx context.Context, db DB, p0 string, p1 int) (string, error) {
	// call public.gen_salt
	const sqlstr = `SELECT * FROM public.gen_salt($1, $2)`
	// run
	var r0 string
	logf(sqlstr, p0, p1)
	if err := db.QueryRowContext(ctx, sqlstr, p0, p1).Scan(&r0); err != nil {
		return "", logerror(err)
	}
	return r0, nil
}
