package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// PgpPubEncryptByTextAndBytea calls the stored function 'public.pgp_pub_encrypt(text, bytea) bytea' on db.
func PgpPubEncryptByTextAndBytea(ctx context.Context, db DB, p0 string, p1 []byte) ([]byte, error) {
	// call public.pgp_pub_encrypt
	const sqlstr = `SELECT * FROM public.pgp_pub_encrypt($1, $2)`
	// run
	var r0 []byte
	logf(sqlstr, p0, p1)
	if err := db.QueryRowContext(ctx, sqlstr, p0, p1).Scan(&r0); err != nil {
		return nil, logerror(err)
	}
	return r0, nil
}

// PgpPubEncryptByTextByteaAndText calls the stored function 'public.pgp_pub_encrypt(text, bytea, text) bytea' on db.
func PgpPubEncryptByTextByteaAndText(ctx context.Context, db DB, p0 string, p1 []byte, p2 string) ([]byte, error) {
	// call public.pgp_pub_encrypt
	const sqlstr = `SELECT * FROM public.pgp_pub_encrypt($1, $2, $3)`
	// run
	var r0 []byte
	logf(sqlstr, p0, p1, p2)
	if err := db.QueryRowContext(ctx, sqlstr, p0, p1, p2).Scan(&r0); err != nil {
		return nil, logerror(err)
	}
	return r0, nil
}
