package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// PgpArmorHeaders calls the stored function 'public.pgp_armor_headers(text) (text, text)' on db.
func PgpArmorHeaders(ctx context.Context, db DB, p0 string) (string, string, error) {
	// call public.pgp_armor_headers
	const sqlstr = `SELECT * FROM public.pgp_armor_headers($1)`
	// run
	var key string
	var value string
	logf(sqlstr, p0)
	if err := db.QueryRowContext(ctx, sqlstr, p0).Scan(&key, &value); err != nil {
		return "", "", logerror(err)
	}
	return key, value, nil
}
