package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// PgpSymDecryptByByteaAndText calls the stored function 'public.pgp_sym_decrypt(bytea, text) text' on db.
func PgpSymDecryptByByteaAndText(ctx context.Context, db DB, p0 []byte, p1 string) (string, error) {
	// call public.pgp_sym_decrypt
	const sqlstr = `SELECT * FROM public.pgp_sym_decrypt($1, $2)`
	// run
	var r0 string
	logf(sqlstr, p0, p1)
	if err := db.QueryRowContext(ctx, sqlstr, p0, p1).Scan(&r0); err != nil {
		return "", logerror(err)
	}
	return r0, nil
}

// PgpSymDecryptByByteaTextAndText calls the stored function 'public.pgp_sym_decrypt(bytea, text, text) text' on db.
func PgpSymDecryptByByteaTextAndText(ctx context.Context, db DB, p0 []byte, p1, p2 string) (string, error) {
	// call public.pgp_sym_decrypt
	const sqlstr = `SELECT * FROM public.pgp_sym_decrypt($1, $2, $3)`
	// run
	var r0 string
	logf(sqlstr, p0, p1, p2)
	if err := db.QueryRowContext(ctx, sqlstr, p0, p1, p2).Scan(&r0); err != nil {
		return "", logerror(err)
	}
	return r0, nil
}
