package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// PgpPubDecryptByByteaAndBytea calls the stored function 'public.pgp_pub_decrypt(bytea, bytea) text' on db.
func PgpPubDecryptByByteaAndBytea(ctx context.Context, db DB, p0, p1 []byte) (string, error) {
	// call public.pgp_pub_decrypt
	const sqlstr = `SELECT * FROM public.pgp_pub_decrypt($1, $2)`
	// run
	var r0 string
	logf(sqlstr, p0, p1)
	if err := db.QueryRowContext(ctx, sqlstr, p0, p1).Scan(&r0); err != nil {
		return "", logerror(err)
	}
	return r0, nil
}

// PgpPubDecryptByByteaByteaAndText calls the stored function 'public.pgp_pub_decrypt(bytea, bytea, text) text' on db.
func PgpPubDecryptByByteaByteaAndText(ctx context.Context, db DB, p0, p1 []byte, p2 string) (string, error) {
	// call public.pgp_pub_decrypt
	const sqlstr = `SELECT * FROM public.pgp_pub_decrypt($1, $2, $3)`
	// run
	var r0 string
	logf(sqlstr, p0, p1, p2)
	if err := db.QueryRowContext(ctx, sqlstr, p0, p1, p2).Scan(&r0); err != nil {
		return "", logerror(err)
	}
	return r0, nil
}

// PgpPubDecryptByByteaByteaTextAndText calls the stored function 'public.pgp_pub_decrypt(bytea, bytea, text, text) text' on db.
func PgpPubDecryptByByteaByteaTextAndText(ctx context.Context, db DB, p0, p1 []byte, p2, p3 string) (string, error) {
	// call public.pgp_pub_decrypt
	const sqlstr = `SELECT * FROM public.pgp_pub_decrypt($1, $2, $3, $4)`
	// run
	var r0 string
	logf(sqlstr, p0, p1, p2, p3)
	if err := db.QueryRowContext(ctx, sqlstr, p0, p1, p2, p3).Scan(&r0); err != nil {
		return "", logerror(err)
	}
	return r0, nil
}
