package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
)

// StreamCred represents a row from 'public.stream_creds'.
type StreamCred struct {
	CustomerID string         `json:"customer_id"` // customer_id
	StreamType StreamType     `json:"stream_type"` // stream_type
	AuthCode   sql.NullString `json:"auth_code"`   // auth_code
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [StreamCred] exists in the database.
func (sc *StreamCred) Exists() bool {
	return sc._exists
}

// Deleted returns true when the [StreamCred] has been marked for deletion
// from the database.
func (sc *StreamCred) Deleted() bool {
	return sc._deleted
}

// Insert inserts the [StreamCred] to the database.
func (sc *StreamCred) Insert(ctx context.Context, db DB) error {
	switch {
	case sc._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case sc._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (manual)
	const sqlstr = `INSERT INTO public.stream_creds (` +
		`customer_id, stream_type, auth_code` +
		`) VALUES (` +
		`$1, $2, $3` +
		`)`
	// run
	logf(sqlstr, sc.CustomerID, sc.StreamType, sc.AuthCode)
	if _, err := db.ExecContext(ctx, sqlstr, sc.CustomerID, sc.StreamType, sc.AuthCode); err != nil {
		return logerror(err)
	}
	// set exists
	sc._exists = true
	return nil
}

// Update updates a [StreamCred] in the database.
func (sc *StreamCred) Update(ctx context.Context, db DB) error {
	switch {
	case !sc._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case sc._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.stream_creds SET ` +
		`stream_type = $1, auth_code = $2 ` +
		`WHERE customer_id = $3`
	// run
	logf(sqlstr, sc.StreamType, sc.AuthCode, sc.CustomerID)
	if _, err := db.ExecContext(ctx, sqlstr, sc.StreamType, sc.AuthCode, sc.CustomerID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [StreamCred] to the database.
func (sc *StreamCred) Save(ctx context.Context, db DB) error {
	if sc.Exists() {
		return sc.Update(ctx, db)
	}
	return sc.Insert(ctx, db)
}

// Upsert performs an upsert for [StreamCred].
func (sc *StreamCred) Upsert(ctx context.Context, db DB) error {
	switch {
	case sc._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.stream_creds (` +
		`customer_id, stream_type, auth_code` +
		`) VALUES (` +
		`$1, $2, $3` +
		`)` +
		` ON CONFLICT (customer_id) DO ` +
		`UPDATE SET ` +
		`stream_type = EXCLUDED.stream_type, auth_code = EXCLUDED.auth_code `
	// run
	logf(sqlstr, sc.CustomerID, sc.StreamType, sc.AuthCode)
	if _, err := db.ExecContext(ctx, sqlstr, sc.CustomerID, sc.StreamType, sc.AuthCode); err != nil {
		return logerror(err)
	}
	// set exists
	sc._exists = true
	return nil
}

// Delete deletes the [StreamCred] from the database.
func (sc *StreamCred) Delete(ctx context.Context, db DB) error {
	switch {
	case !sc._exists: // doesn't exist
		return nil
	case sc._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.stream_creds ` +
		`WHERE customer_id = $1`
	// run
	logf(sqlstr, sc.CustomerID)
	if _, err := db.ExecContext(ctx, sqlstr, sc.CustomerID); err != nil {
		return logerror(err)
	}
	// set deleted
	sc._deleted = true
	return nil
}

// StreamCredByCustomerID retrieves a row from 'public.stream_creds' as a [StreamCred].
//
// Generated from index 'stream_creds_pkey'.
func StreamCredByCustomerID(ctx context.Context, db DB, customerID string) (*StreamCred, error) {
	// query
	const sqlstr = `SELECT ` +
		`customer_id, stream_type, auth_code ` +
		`FROM public.stream_creds ` +
		`WHERE customer_id = $1`
	// run
	logf(sqlstr, customerID)
	sc := StreamCred{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, customerID).Scan(&sc.CustomerID, &sc.StreamType, &sc.AuthCode); err != nil {
		return nil, logerror(err)
	}
	return &sc, nil
}

// Customer returns the Customer associated with the [StreamCred]'s (CustomerID).
//
// Generated from foreign key 'fk_customer'.
func (sc *StreamCred) Customer(ctx context.Context, db DB) (*Customer, error) {
	return CustomerByCustomerID(ctx, db, sc.CustomerID)
}
