Frontend Application
Backend Service

Cloud: {
  Spotify Servers
  Tidal Servers
  Jellyfin Servers
}

Frontend Application -> Backend Service: API Requests
Backend Service -> Frontend Application: API Response
Backend Service -> Frontend Application: Stream music data

Backend Service -> Cloud.Spotify Servers
Backend Service -> Cloud.Tidal Servers
Backend Service -> Cloud.Jellyfin Servers
